name: Build and release

on: push

concurrency:
  group: build-and-release
  cancel-in-progress: true

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Install Node.js and npm
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Build and release the app
        run: npm package:publish
        env:
          GH_TOKEN: ${{ secrets.github_token }}
