name: Test

on:
  push:
    branches:
      - main

concurrency:
  group: test
  cancel-in-progress: true

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Install Node.js and npm
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build bundles for jest setup
        run: npm run build

      - name: Lint
        run: npm run lint

      - name: Typecheck
        run: npm exec tsc

      - name: Run tests
        run: npm test
